add_newline = false
scan_timeout = 10

format = """
$username$directory$git_branch$git_status$time$character"""

right_format = """$battery$status"""

# 393233
# CFCCCC
# 2E326E
# 82272A

[username]
format = "[](fg:#CFCCCC)[ $user ](fg:#393233 bg:#CFCCCC bold)[ ](fg:#CFCCCC bg:#2E326E bold)"
show_always = true
disabled = false

[directory]
format = "[$home_symbol](fg:#CFCCCC bg:#2E326E)[$path](fg:#CFCCCC bg:#2E326E)[$read_only](fg:#CFCCCC bg:#2E326E)[ ](fg:#2E326E bg:#675E3F bold)"
truncation_symbol = "…/"
truncate_to_repo = false
truncation_length = 100
home_symbol = " "

[git_branch]
format = "[$symbol](fg:#CFCCCC bg:#675E3F)[$branch](fg:#CFCCCC bg:#675E3F)[ ](fg:#675E3F bg:#CFCCCC bold)"
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]](fg:#82272A bg:#CFCCCC))'

[time]
format = '[ \[$time\] ](fg:#393233 bg:#CFCCCC)'
utc_time_offset = "local"
time_format = "%T"
disabled = false
time_range = "-"

[character]
success_symbol = "[  ](bold fg:#393233 bg:#CFCCCC)[](bg:#CFCCCC)[](fg:#CFCCCC bold)"
error_symbol = "[  ](bold fg:#393233 bg:#CFCCCC)[](bg:#CFCCCC)[](fg:#CFCCCC bold)"

[battery]
full_symbol = " "
format = "[](fg:#CFCCCC)[ $symbol$percentage ](fg:#82272A bg:#CFCCCC)[](fg:#CFCCCC bold)"

[[battery.display]]
threshold = 100
